"""
    QUESTION 1 EASY
    #SWAP ALL TARGET  MATCHING ELEMENTS FROM A LIST 

    EG: LST=[1,2,2,4,5]
    USER INPUT VALUES
    TARGET=2
    NEW_VALUE=8
    OUTPUT:[1,8,8,4,5]
    NO PRE BUILT FUNCTION



    QUESTION 2 EASY
    ROTATE ARRAY(LIST)LETFT->RIGHT WITH A DELIMETER TO DIVIDE |
    ARR=[1,2,3,4,5,6,7,8]
    OUTPUT=[5,6,7,8,"|",1,2,3,4]
    NO PRE BUILT FUNCTION

    

    QUESTION 3 EASY
    COUNT TOTAL CHARACTERS IN STRING INCLUDING SPACES
    STRING WILL BE USERINPUT
    EG: STR="PYTHON PROGRAMMING"
        OUTPUP=18
    DO NOT USE LEN FUNCTION



    QUESTION 4 INTERMEDIATE

    TAKE BASIC FORM INFORMATION FROM USER AND SAVE AS A DICTIONARY NAMED FORM_DATA

    OUTPUT:
    {
    NAME: 
    AGE:
    MOB-NO: 
    GENDER:
    }


    
    QUESTION 5 INTERMEDIATE

    FORM A DICTIONARY PRINT KEY AND VALUES ONLY OF THOSE WHICH ARE INTEGER

     {
    NAME: STR
    AGE: INT   <-
    MOB-NO: INT  <-
    GENDER:CHAR
    }


    

    


"""